### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ldangelo** [JetBrains/hackathon-Embeditor#4]
Is there any documentation on using this?  I would like to try this out and potentially try and make it work with emacs as well.

I would be happy to write something up if I could get some pointers on how to get it installed?

**Comment by farfanoide** [comment]
any updates?

**Comment by zolotov** [comment]
Here is small reference. I don't think the project needs more documentation because it's really small and it's easier to read the code, in the second we don't plan to develop it.

The project consists of two parts.

First part is about embedding vim into IDE plugin
- embeditor – IntelliJ plugin which allow you to embed real vim into IDE editor
- vim-embeditor-plugin - Vim plugin

And I can't tell anything about it.

The second part is about using IDEA resolution/completion mechanisms in vim.

At the moment vim-plugin uses simple completion api (see :h completefunc), you can use any other. 
You can run IDEA in headless mode but anyway you need to configure your project at first in IDE and only then run IDE with java.awt.headless=true argument. 

How you can run it and improve. 
First of all open the cloned project in IDEA and configure IDEA SDK.

There are two directories that you need: 

1. vim-intellij-client/. It’s vim plugin written in VimL and Python which makes some xml-rpc to idea. It can retrieve completion variants from IDEA and resolve entity at caret via IDEA. In the both variants it sends to idea content of current file (because it can be not saved yet) and caret offset. 

2. embeditorRPC/. It’s intellij plugin consisted of only 5 files. The most important file is EmbeditorRequestHandler.java – RPC handler that able to provide completion start offset (it can be important for some languages), completion variants and resolving variants. 

Run ‘embeditorRPC’ in IDEA, open and configure the project that you want to edit and attach vim-intellij-client plugin to vim and try to complete something in the project from vim (C-X C-U) or to resolve something (g[). 

Note that xml-rpc port is hardcoded in vim-plugin (63341) and it also hardcoded in embeditorRPC run configuration (-Drpc.port). The default port of IDEA RPC server is 63342.
